apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: gitlab
data:
  external_scheme: https
  external_hostname: git.192.168.64.19.xip.io
  registry_external_scheme: https
  registry_external_hostname: registry.192.168.64.19.xip.io
  postgres_user: gitlab
  postgres_db: gitlab_production
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: gitlab
data:
  postgres_password: +BP52QIxpT/flVCMpL3KXA==
  initial_shared_runners_registration_token: 49uf3mzs1qdz5vgo
