apiVersion: v1
kind: Service
metadata:
  name: gitlab-nodeport
  namespace: gitlab
  labels:
    name: gitlab
spec:
  type: NodePort
  selector:
    name: gitlab
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
    - name: mattermost
      port: 8065
      targetPort: mattermost
    - name: registry
      port: 8105
      targetPort: registry
    - name: workhorse
      port: 8005
      targetPort: workhorse
