apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-docker
  namespace: gitlab
data:
  entrypoint: |
    #!/bin/bash

    # Register the runner
    /entrypoint register --non-interactive -u http://gitlab.gitlab/ci -r '49uf3mzs1qdz5vgo' --docker-image 'ruby:2.3' --executor kubernetes

    # Start the runner
    /entrypoint run --user=gitlab-runner --working-directory=/home/gitlab-runner
  config.toml: |
    concurrent = 10
    check_interval = 1

    [[runners]]
      name = "gitlab-docker-runner"
      url = "http://gitlab.gitlab/ci"
      token = ""
      executor = "kubernetes"
      [runners.kubernetes]
      image = "ruby:2.3"
