apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab
data:
  entrypoint: |
    #!/bin/bash

    set -xe

    # Register the runner
    /entrypoint register --non-interactive \
      --url http://gitlab.gitlab/ci \
      --docker-image 'ruby:2.3' \
      --executor kubernetes \
      --kubernetes-privileged=true

    # Start the runner
    /entrypoint run --user=gitlab-runner \
      --working-directory=/home/gitlab-runner
  config.toml: |
    concurrent = 10
    check_interval = 1
