apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    name: gitlab
spec:
  rules:
  - host: git.35.186.201.110.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  namespace: gitlab
  labels:
    name: gitlab
spec:
  rules:
  - host: registry.35.186.201.110.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mattermost
  namespace: gitlab
  labels:
    name: gitlab
spec:
  rules:
  - host: mattermost.35.186.201.110.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
