apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    name: gitlab
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - gitlab.gke.twkie.net
    secretName: gitlab-tls
  rules:
  - host: gitlab.gke.twkie.net
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 8005
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  namespace: gitlab
  labels:
    name: gitlab
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - registry.gke.twkie.net
    secretName: registry-tls
  rules:
  - host: registry.gke.twkie.net
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 8105
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mattermost
  namespace: gitlab
  labels:
    name: gitlab
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - mattermost.gke.twkie.net
    secretName: mattermost-tls
  rules:
  - host: mattermost.gke.twkie.net
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 8065
