apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    name: gitlab
spec:
  rules:
  - host: git.192.168.64.19.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
  - host: registry.192.168.64.19.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
  - host: mattermost.192.168.64.19.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
