apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    name: gitlab
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: git.104.155.5.78.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  namespace: gitlab
  labels:
    name: gitlab
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: registry.104.155.5.78.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mattermost
  namespace: gitlab
  labels:
    name: gitlab
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: mattermost.104.155.5.78.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
